service: cognition-catalog
provider:
  name: aws
  region: us-east-1
  runtime: python3.6
  iamRoleStatementsName: cognition-catalog-role
  iamRoleStatements:
    - Action:
        - sns:*
        - sqs:*

resources:
  Resources:

    NewSTACItemTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: NewSTACItemTopic

    NewSTACItemQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: NewSTACItemQueue